language: node_js

node_js:
  - 'stable'
before_install:
  - 'cd client'

before_script:
  - 'npm install'

script:
  - 'npm run lint'
  - 'npm run generate'

deploy:
  provider: surge
  project: ./dist/
  domain: jt-jetflix.surge.sh