language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run generate
deploy:
  provider: surge
  skip_cleanup: true
  domain: jt-jetflix.surge.sh
  project: ./client/dist/
on:
  branch: master